version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@3.0.0
  # different jobs are calles later in the workflows sections
jobs:
  aws-cli-iam-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: deploy to s3
          command: |
            npm run frontend:deploy      
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: frontend_install
          command: |
            npm run frontend:install
      - run:
          name: backend_install
          command: |
            npm run backend:install
      - run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV

      - run:
          name: build_backend
          command: |
            npm run backend:build
      - run:
          name: build_frontend
          command: |
            npm run frontend:build
workflows:
  build-and-aws-cli-setup-and-deploy:
    jobs:
      - build
      - aws-cli-iam-setup
      - deploy
